# Generated by Django 4.1.4 on 2024-08-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('task_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, '待处理'), (1, '处理中'), (2, '已完成')], default=0)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_item',
            },
        ),
    ]
