# Generated by Django 4.1.4 on 2024-08-11 03:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_taskitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='task_item_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
    ]
