# Generated by Django 4.1.4 on 2024-08-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_taskitem_task_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('ongoing', '处理中'), ('failed', '失败'), ('prime', '待编辑'), ('done', '已完成')], default='pending', max_length=16),
        ),
    ]
