# Generated by Django 4.1.4 on 2025-03-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0003_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='ai_response',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user_input',
        ),
        migrations.AddField(
            model_name='conversation',
            name='dialogue',
            field=models.TextField(blank=True, null=True, verbose_name='<UNK>'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='system',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='system设置'),
        ),
    ]
