# Generated by Django 4.1.4 on 2025-03-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0004_remove_conversation_ai_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='system',
            field=models.TextField(blank=True, null=True, verbose_name='system设置'),
        ),
    ]
